config/routes.rb
Rails.application.routes.draw do
  root 'subtokens#new'

  get '/', to: 'subtokens#new'
  post '/token', to: 'subtokens#token', as: 'token'
  post '/permissions', to: 'subtokens#permissions', as: 'permissions'
  post '/urls', to: 'subtokens#urls', as: 'urls'
  post '/expiry', to: 'subtokens#expiry', as: 'expiry'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/subtokens_controller.rb
# frozen_string_literal: true

# Main controller of the app, deals with the entire lifecycle of creating
# subtokens.
class SubtokensController < ApplicationController
  ALL_PERMISSIONS = %w[
    account
    builds
    characters
    guilds
    inventories
    progression
    pvp
    tradingpost
    unlocks
    wallet
  ].freeze

  KNOWN_ENDPOINTS = %w[
    /v2/account
    /v2/account/achievements
    /v2/account/bank
    /v2/account/dailycrafting
    /v2/account/dungeons
    /v2/account/dyes
    /v2/account/finishers
    /v2/account/gliders
    /v2/account/home/cats
    /v2/account/home/nodes
    /v2/account/inventory
    /v2/account/luck
    /v2/account/mailcarriers
    /v2/account/mapchests
    /v2/account/masteries
    /v2/account/mastery/points
    /v2/account/materials
    /v2/account/minis
    /v2/account/mounts/skins
    /v2/account/mounts/types
    /v2/account/novelties
    /v2/account/outfits
    /v2/account/pvp/heroes
    /v2/account/raids
    /v2/account/recipes
    /v2/account/titles
    /v2/account/wallet
    /v2/account/worldbosses
  ].freeze

  def new
    session.clear
    session[:stage] = 1
  end

  def token
    @stage = 2
    tokeninfo = Gw2api.tokeninfo(params[:base_api_token])
    if tokeninfo.nil?
      flash.now[:stage_1] = 'Invalid API key!'
    else
      session[:api_token] = params[:base_api_token]
      session[:token_permissions] = tokeninfo['permissions'].sort
      session[:stage] = 2
    end
    render :new
  end

  def permissions
    session[:stage] = 3
    session[:set_permissions] = ['account']
    ALL_PERMISSIONS.each do |perm|
      session[:set_permissions] << perm if params[perm].present?
    end
    session[:set_permissions].uniq!
    session[:set_permissions].sort!

    if session[:set_permissions].empty?
      flash.now[:stage_2] = 'You must select at least one permission!'
    end

    @known_endpoints = KNOWN_ENDPOINTS
    render :new
  end

  def urls
    urls = []
    unless params[:all_endpoints].present?
      params.each do |k, v|
        next unless v.is_a?(String) && k.starts_with?('known-')

        idx = k[6..].to_i
        urls << KNOWN_ENDPOINTS[idx] unless idx > KNOWN_ENDPOINTS.count
      end

      custom = params[:custom_urls]
      urls |= custom.split("\r\n") if custom&.present?

      if urls.empty?
        flash.now[:stage_4] = 'You deselected "Enable All URLs", but did not select any endpoints. All endpoints will be available.'
      end
    end

    session[:stage] = 4
    session[:set_urls] = urls.uniq.sort

    @default_expiry = 30.days.from_now.strftime('%Y-%m-%d %H:%M:%S')

    render :new
  end

  def expiry
    expiry = params[:expiry]
    expiry = nil if expiry.blank?

    token_params = {
      access_token: session[:api_token],
      permissions: session[:set_permissions].join(',')
    }

    if session[:set_urls].count > 0
      token_params[:urls] = session[:set_urls].join(',')
    end

    if expiry
      token_params[:expire] = DateTime.parse(expiry).iso8601(6)
    end

    data = Gw2api.createsubtoken(token_params)
    @subtoken = data['subtoken']

    session.clear
    session[:stage] = 5
    render :new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subtokens_helper.rb
module SubtokensHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SubToken Generator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/subtokens/_stage_1.html.erb
<div class="stage-container">
  <div class="stage-marker">
    <div class="stage-number-container">
      <span class="stage-number">1</span>
    </div>
    <span class="stage-title">Enter API Token</span>
  </div>
  <% if session[:stage] == 1 %>
    <div class="stage-body">
      <div class="stage-gutter"></div>
      <div class="stage-contents">
        <%= render partial: 'stage_errors', locals: { errors: flash[:stage_1] } %>
        <p class="stage-description">
          Enter your API Token your new Subtoken will be based on.
        </p>
        <%= form_tag token_path do %>
          <%= text_field_tag :base_api_token, '', placeholder: 'API Token' %>
          <%= submit_tag 'Continue' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/subtokens/_stage_2.html.erb
<div class="stage-container">
  <div class="stage-marker">
    <div class="stage-number-container">
      <span class="stage-number">2</span>
    </div>
    <span class="stage-title">Select Permissions</span>
  </div>
  <% if session[:stage] == 2 %>
    <div class="stage-body">
      <div class="stage-gutter"></div>
      <div class="stage-contents">
        <%= form_tag permissions_path do %>
          <ul>
            <% session[:token_permissions].each do |perm| %>
              <li>
                <%= check_box_tag perm.to_sym, 1, perm == 'account', disabled: perm == 'account' %>
                <%= label_tag perm.to_sym, perm %>
              </li>
            <% end %>
          </ul>
          <%= submit_tag 'Continue' %>
        <% end %>
     </div>
    </div>
  <% end %>
</div>

app/views/subtokens/_stage_3.html.erb
<div class="stage-container">
  <div class="stage-marker">
    <div class="stage-number-container">
      <span class="stage-number">3</span>
    </div>
    <span class="stage-title">Select URLs</span>
  </div>
  <% if session[:stage] == 3 %>
    <div class="stage-body">
      <div class="stage-gutter"></div>
      <div class="stage-contents">
        <%= form_tag urls_path do %>
          <%= check_box_tag :all_endpoints, 1, true, class: 'all-endpoints-enabler' %>
          <%= label_tag :all_endpoints, 'Enable all URLs' %>
          <br/>
          <div class="collapsible-container endpoint-group">
            <input id="collapser" type="checkbox" class="collapsible-toggler"/>
            <label for="collapser" class="collapsible-toggler-label">Known Endpoints</label>
            <div class="collapsible-content">
              <div class="content-inner">
                <ul>
                  <% @known_endpoints.each_with_index do |endpoint, idx| %>
                    <li>
                      <%= check_box_tag "known-#{idx}" %>
                      <%= label_tag "known-#{idx}", endpoint %>
                    </li>
                  <% end %>
                </ul>
             </div>
            </div>
          </div>
          <div class="collapsible-container endpoint-group">
            <input id="collapser2" type="checkbox" class="collapsible-toggler"/>
            <label for="collapser2" class="collapsible-toggler-label">Custom Endpoints</label>
            <div class="collapsible-content">
              <div class="content-inner">
                <%= text_area_tag :custom_urls %><br/>
                Enter one endpoint on each line.<br/>
              </div>
            </div>
          </div>
          <%= submit_tag 'Continue' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/subtokens/_stage_4.html.erb
<div class="stage-container">
  <div class="stage-marker">
    <div class="stage-number-container">
      <span class="stage-number">4</span>
    </div>
    <span class="stage-title">Select Expire Time</span>
  </div>
  <% if session[:stage] == 4 %>
    <div class="stage-body">
      <div class="stage-gutter"></div>
      <div class="stage-contents">
        <%= render partial: 'stage_errors', locals: { errors: flash[:stage_4] } %>
        <strong>Expiration Date:</strong><br/>
        <%= form_tag expiry_path do %>
          <%= text_field_tag :expiry, @default_expiry %><br/>
          YYYY-MM-DD HH:MM:SS format.<br/>
          Leave blank for no expiration date.<br/>
          <%= submit_tag 'Finish' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/subtokens/_stage_5.html.erb
<div class="stage-container">
  <div class="stage-marker">
    <div class="stage-number-container">
      <span class="stage-number">5</span>
    </div>
    <span class="stage-title">Copy Subtoken</span>
  </div>
  <% if session[:stage] == 5 %>
    <div class="stage-body">
      <div class="stage-gutter"></div>
      <div class="stage-contents">
        <%= text_field_tag :subtoken, @subtoken %>
      </div>
    </div>
  <% end %>
</div>

app/views/subtokens/_stage_errors.html.erb
<% if errors.present? %>
  <div class="stage-errors">
    <span class="stage-error"><%= errors %></span>
  </div>
<% end %>

app/views/subtokens/create.html.erb
<%= @data %>

app/views/subtokens/new.html.erb
<div class="page-container">
  <div class="page-header">
    <h2 class="page-title">
      <%= link_to 'Subtoken Generator', root_path %>
    </h2>
    <p class="page-description">
      You can generate subtokens with this tool.
      Subtokens are a way to restrict the permissions of
      a regular GW2 API Token to a specific subset.
    </p>
  </div>
  <div class="main-container">
    <%= render 'stage_1' %>
    <%= render 'stage_2' %>
    <%= render 'stage_3' %>
    <%= render 'stage_4' %>
    <%= render 'stage_5' %>
  </div>
</div>